// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gopoints.proto

package gopoints

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing user's name
type PointRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointRequest) Reset()         { *m = PointRequest{} }
func (m *PointRequest) String() string { return proto.CompactTextString(m) }
func (*PointRequest) ProtoMessage()    {}
func (*PointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gopoints_600608dbe04d2973, []int{0}
}
func (m *PointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointRequest.Unmarshal(m, b)
}
func (m *PointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointRequest.Marshal(b, m, deterministic)
}
func (dst *PointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointRequest.Merge(dst, src)
}
func (m *PointRequest) XXX_Size() int {
	return xxx_messageInfo_PointRequest.Size(m)
}
func (m *PointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointRequest proto.InternalMessageInfo

func (m *PointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing random point
type PointReply struct {
	Point                string   `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointReply) Reset()         { *m = PointReply{} }
func (m *PointReply) String() string { return proto.CompactTextString(m) }
func (*PointReply) ProtoMessage()    {}
func (*PointReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gopoints_600608dbe04d2973, []int{1}
}
func (m *PointReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointReply.Unmarshal(m, b)
}
func (m *PointReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointReply.Marshal(b, m, deterministic)
}
func (dst *PointReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointReply.Merge(dst, src)
}
func (m *PointReply) XXX_Size() int {
	return xxx_messageInfo_PointReply.Size(m)
}
func (m *PointReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PointReply.DiscardUnknown(m)
}

var xxx_messageInfo_PointReply proto.InternalMessageInfo

func (m *PointReply) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

func init() {
	proto.RegisterType((*PointRequest)(nil), "PointRequest")
	proto.RegisterType((*PointReply)(nil), "PointReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoPointsClient is the client API for GoPoints service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoPointsClient interface {
	// Get random point
	GetPoint(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointReply, error)
}

type goPointsClient struct {
	cc *grpc.ClientConn
}

func NewGoPointsClient(cc *grpc.ClientConn) GoPointsClient {
	return &goPointsClient{cc}
}

func (c *goPointsClient) GetPoint(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointReply, error) {
	out := new(PointReply)
	err := c.cc.Invoke(ctx, "/GoPoints/GetPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoPointsServer is the server API for GoPoints service.
type GoPointsServer interface {
	// Get random point
	GetPoint(context.Context, *PointRequest) (*PointReply, error)
}

func RegisterGoPointsServer(s *grpc.Server, srv GoPointsServer) {
	s.RegisterService(&_GoPoints_serviceDesc, srv)
}

func _GoPoints_GetPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPointsServer).GetPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoPoints/GetPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPointsServer).GetPoint(ctx, req.(*PointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoPoints_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GoPoints",
	HandlerType: (*GoPointsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPoint",
			Handler:    _GoPoints_GetPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gopoints.proto",
}

func init() { proto.RegisterFile("gopoints.proto", fileDescriptor_gopoints_600608dbe04d2973) }

var fileDescriptor_gopoints_600608dbe04d2973 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcf, 0x2f, 0xc8,
	0xcf, 0xcc, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0x09, 0x00,
	0xf1, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x25, 0x2e, 0x2e, 0xa8, 0x9a, 0x82,
	0x9c, 0x4a, 0x21, 0x11, 0x2e, 0x56, 0xb0, 0x09, 0x50, 0x25, 0x10, 0x8e, 0x91, 0x09, 0x17, 0x87,
	0x7b, 0x3e, 0x58, 0x55, 0xb1, 0x90, 0x06, 0x17, 0x87, 0x7b, 0x6a, 0x09, 0x98, 0x23, 0xc4, 0xab,
	0x87, 0x6c, 0xbc, 0x14, 0xb7, 0x1e, 0xc2, 0x24, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x23, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0x1a, 0xc2, 0x53, 0x96, 0x00, 0x00, 0x00,
}
