// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi A Todo list application
From the todo list tutorial gojek


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/com.gojek.todo-list.v1+json

    Produces:
    - application/com.gojek.todo-list.v1+json

swagger:meta
*/
package restapi
